# Generated by Django 3.2.5 on 2021-07-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
