# Generated by Django 3.2.5 on 2021-07-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0003_auto_20210721_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('BOUGHT', 'BOUGHT'), ('NOT AVAILABLE', 'NOT AVAILABLE')], default='PENDING', max_length=20),
        ),
    ]
