# Generated by Django 3.2.5 on 2021-08-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0004_alter_additem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='date',
            field=models.DateField(),
        ),
    ]
